config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :users, only: [:show]
  resources :players do
    resources :events, only: [:new, :create]
  end
  get "/profile", to: 'pages#profile'
  resources :events, only: :update do
    member do
      patch "acceptordeny"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :player
  belongs_to :user
  # before_validation :update_status
  # def update_status
  #   self.status ||= "pending"
  ##   self.status = self.status || "pending"
  # end
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :events
  belongs_to :user
  validates :nickname, presence: true, uniqueness: true
  validates :gender, presence: true
  validates :price, presence: true
  validates :category, presence: true, inclusion: { in: %w(Video-Games Card-Games Board-Games Role-Playing-Games), message: "%{value} is not a valid category"}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events
  has_many :players, dependent: :destroy
  validates :name, :age, :genre, presence: true
  validates :bio, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :bio, :age, :genre])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :bio, :age, :genre])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
    # binding.pry
    @player = Player.find(params[:player_id])
  end

  def create
    @event = Event.new(event_params)
    @player = Player.find(params[:player_id])
    @event.player = @player
    @event.user = current_user
    @event.status = "pending"
    @event.total_price = @event.duration * @event.player.price

    redirect_to profile_path and return if @event.save

    render 'new'
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(status: params[:event][:status])
      flash[:success] = "Noted!"
      redirect_to profile_path
    else
      flash[:error] = "Wow you're not really good at this, are you?"
      render 'profile'
    end
  end

  def acceptordeny
    @event = Event.find(params[:id])
    @event.update(status: params[:status])
    redirect_to profile_path
  end
  

  # def destroy
  #   @event = Event.find(params[:id])
  #   if @event.status == "refuse"
  #     flash[:success] = 'Bonne route, camarade...'
  #   elsif @event.status == "cancel"
  #     flash[:success] = 'Bonne route, camarade...'
  #   else
  #     flash[:error] = 'Les adieux sont difficiles?'
  #   end
  #   redirect_to root_path
  # end

  private

  def event_params
    params.require(:event).permit(:title, :descritption, :start_date, :finish_date, :duration, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end

  def profile
    @players = Player.where(user_id: current_user)
    @events = Event.where(user_id: current_user)
    @books = Event.where(player_id: current_user.players)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    # appeler le user?
    if params[:q].present?
      @players = Player.where(category: params[:q]).order("id DESC")
    else
      @players = Player.all.order("id DESC")
    end
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    @player.user = current_user
    @player.price = 

    if @player.save
      flash[:success] = "Welcome, #{@player.nickname} !"
      redirect_to @player
    else
      flash[:error] = "Hey peasant, you made a mistake.."
      render 'new'
    end
  end

  def show
    @player = Player.find(params[:id])
    @user = @player.user
  end

  def destroy
    @player = Player.find(params[:id])
    if @player.destroy
      flash[:success] = 'Goodbye buddy...'
    else
      flash[:error] = "You don't want to leave us?"
    end
    redirect_to root_path
  end

  private

  def player_params
    params.require(:player).permit(:id, :category, :nickname, :price, :gender)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @players = @user.players
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:success] = 'Goodbye buddy...'
    else
      flash[:error] = "You don't want to leave us?"
    end
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/new.html.erb
<%= simple_form_for [@player, @event] do |f| %>
  <%= f.input :title %>
  <%= f.input :descritption %>
  <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
  <%= f.input :finish_date, as: :string, required: false, input_html: {class: "datepicker"} %>
  <%= f.input :duration %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BOREDGames</title>
    <script src="https://kit.fontawesome.com/d497f9f72e.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-container">
  <div class="home-intro">
  <h3><strong>Welcome Adventurer !</strong></h3>
    <h4>Our mission is to help you to find some buddies to play with. On our website you can :</h4>
    <p>- Create your players according to several categories and an invitation to join a team should not take long!<br>
    - Choose a player you like to send him an invitation to join your team!</p>
  </div>
      <div class="search-btn"><a href="/players" class="btn btn-success lg"><strong>See all players</strong></a></div>
        <div class="card-categories">
          <%= link_to players_path(q: "Video-Games"), class:"card-category" do %>
            <div >Video Games</div>
          <% end %>
          <%= link_to players_path(q: "Card-Games"), class:"card-category2" do %>
            <div>Card Games</div> 
          <% end %>
          <%= link_to players_path(q: "Board-Games"), class:"card-category3" do %>
            <div>Board Games</div> 
          <% end %>
          <%= link_to players_path(q: "Role-Playing-Games"), class:"card-category4" do %>
            <div>Role Playing Games</div> 
          <% end %>
        </div>
</div>

<%#= link_to 'destroy_user_session', destroy_user_session_path, method: :delete %>

app/views/pages/profile.html.erb
<div class="profile-container">
  <div class="profile-info">
    <h1><%= current_user.name %></h1>
      <p><strong>Age : </strong><%= current_user.age %></p>
      <p><strong>Gender : </strong><%= current_user.genre %></p>
      <p><strong>Bio : </strong><%= current_user.bio %></p>  
  </div>
  <h2 class="player-profile">Player Cards</h2>
  <div class="cards-container">
    <div class="cards">
    <% @players.each do |player| %>
        <%= link_to player_path(player) do %>
            <% user = player.user %>
                <article class="card">
                    <header>
                        <h2><%= player.nickname %></h2>
                    </header>
                    <% if player.gender == "Male" %>
                        <%= image_tag "male_avatar.png" %>
                    <% else %>
                        <%= image_tag "female_avatar.jpg" %>
                    <% end %>
                    <div class="content">
                        <p>Category : <%= player.category %> </p>
                    </div>    
                </article>
            <% end %>
        <% end %>
    </div>
  </div>
  <div class="book-event">
  <h2>I booked them :</h2>
  
  <% @events.each do |event| %>
    <p><strong>Title : </strong><%= event.title %></p>
    <p><strong>Description : </strong><%= event.descritption %></p>
    <p><strong>Date : </strong><%= event.start_date %> ==> <%= event.finish_date %></p> 
    <p><strong>Player : </strong><%= link_to event.player.nickname, player_path(event.player_id) %></p>
    <p><strong>Expected duration : </strong><%= event.duration %></p>
    <p><strong>Event status : </strong>
      <%= link_to "accept",acceptordeny_event_path(event, status: "accepted"), method: :patch  %>
      <%= link_to "cancel",acceptordeny_event_path(event, status: "cancelled"), method: :patch  %>
      <p><%= event.status %></p>
      <p><strong>Total price : </strong><%= event.total_price %></p>
  <% end %>
  
  <h2>They booked me :</h2>
  
  <% @books.each do |book| %>
    <p><strong>Title : </strong><%= book.title %>
    <p><strong>Description : </strong><%= book.descritption %></p>
    <p><strong>Date : </strong><%= book.start_date %> ==> <%= book.finish_date %></p>
    <p><strong>Player : </strong><%= link_to book.player.nickname, player_path(book.player_id) %></p>
    <p><strong>Expected duration : </strong><%= book.duration %></p>
    <p><strong>Event status : </strong>
    <%= link_to "accept",acceptordeny_event_path(book, status: "accepted"), method: :patch  %>
    <%= link_to "refuse",acceptordeny_event_path(book, status: "refused"), method: :patch  %>
    <p><%= book.status %></p>
  <% end %>
  
  <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
</div>

app/views/players/index.html.erb
<div class="cards-container">
    <div class="cards">
    <% @players.each do |player| %>
        <%= link_to player_path(player) do %>
            <% user = player.user %>
                <article class="card">
                    <header>
                        <h2><%= player.nickname %></h2>
                    </header>
                    <% if player.gender == "Male" %>
                        <%= image_tag "male_avatar.png" %>
                    <% else %>
                        <%= image_tag "female_avatar.jpg" %>
                    <% end %>
                    <div class="content">
                        <p>Category : <%= player.category %> </p>
                    </div>    
                </article>
            <% end %>
        <% end %>
    </div>
</div>

app/views/players/new.html.erb
<div class="create-player-container">
  <div class="form-border">
    <%= simple_form_for @player do |f| %>
      <%= f.input :category, collection: ["Video-Games", "Card-Games", "Board-Games", "Role-Playing-Games"] %>
      <%= f.input :nickname %>
      <%= f.input :price %>
      <%= f.input :gender, collection: ["Male", "Female"] %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/players/show.html.erb
<div class="bigger-container">
  <div class="show-player-container">
    <h1>Bow to me, the incredible <strong><%= @player.nickname %></strong></h1>
      <p class="awesome">I am awesome at : </p>
      <p class="categ"><i class="fas fa-bolt"></i><%= @player.category %><i class="fas fa-bolt"></i></p>
      <p class="user-link">More about me, the very awesome <%= @player.nickname %>, also known as :<br> <strong><%= link_to @player.user.name, user_path(@user) %></strong></p>
      <% if @player.user != current_user %>
        <%= link_to "Book me ❤" , new_player_event_path(@player), data: { turbolinks: 'false' } %><p class="price-string">for the low, low price of <%= @player.price %> euros!</p>
      <% else %>
        <%= link_to "My upcoming game nights 🎲" , profile_path %>
      <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This website is made by Mar_ae, RenéDuTerTer et Logosh
  </div>
</div>

app/views/shared/_navbar.html.erb
  <div class="nav-bar">
    <h1>If you're bored to play alone !</h1>
      <i class="fas fa-users">
        <%= link_to "Bored Games", root_path %>
      </i>
      <div class="user-nav">
        <%= link_to "Create a player", new_player_path, class: "player-create" %>
        <% if current_user %>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Log In", profile_path %>
        <% end %>
        <%= link_to profile_path do %>
          <%= image_tag "https://eu.ui-avatars.com/api/?name=Captain+Price", class: "user-avatar" %>
        <% end %>
      </div>
  </div>

app/views/users/index.html.erb
<h1>Users</h1>


<ul>
  <% @users.each do |user| %>
    <li>Name : <%= user.name %></li>
  <% end %>
</ul>

app/views/users/show.html.erb
  <div class="profile-info">
<h1><%= @user.name %></h1>
<p>Age : <%= @user.age %></p>
<p>Gender : <%= @user.genre %></p>
<p>Bio : <%= @user.bio %></p>
  </div>
<h2>Player Profile</h2>
<div class="cards-container">
    <div class="cards">
    <% @players.each do |player| %>
        <%= link_to player_path(player) do %>
            <% user = player.user %>
                <article class="card">
                    <header>
                        <h2><%= player.nickname %></h2>
                    </header>
                    <% if player.gender == "Male" %>
                        <%= image_tag "male_avatar.png" %>
                    <% else %>
                        <%= image_tag "female_avatar.jpg" %>
                    <% end %>
                    <div class="content">
                        <p>Category : <%= player.category %> </p>
                    </div>    
                </article>
            <% end %>
        <% end %>
    </div>
</div>